---
title: "Inflation of Type I error in One Sample test"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 6.5, fig.width = 8)
```


```{r}
#setwd("/Users/benedictkongyir/Desktop/OSU/Research/Permutation Test/New Simulations/cluster/Results")
load("/Users/benedictkongyir/Desktop/OSU/Research/Permutation Test/New Simulations/cluster/Parrel_sim_RData/OneSamples_power_norm_par.RData")
load("/Users/benedictkongyir/Desktop/OSU/Research/Permutation Test/New Simulations/cluster/Parrel_sim_RData/OneSample_error_inflation.RData")
```



```{r}
data_powertest <-data.frame(power_norm.test_par)
data_error <-data.frame(-(error_inflation))
#data.combine <- data.frame(data_powertest, data_powerloss)
```

 

### Utility of SW test---Normal Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Standard.Normal.SW, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... Normal Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of SW test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Standard.Normal.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of SW test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```



### Utility of SW test---t Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$t.SW, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... t Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of SW test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$t.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of SW test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```


### Utility of SW test---Uniform Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Uniform.SW, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... Uniform Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of SW test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Uniform.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of SW test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```




### Utility of KS test---Normal Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Standard.Normal.KS, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... Normal Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of KS test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Standard.Normal.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of KS test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```



### Utility of KS test---t Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$t.KS, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... t Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of KS test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$t.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02), 
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of KS test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```


### Utility of KS test---Uniform Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Uniform.KS, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of SW test ... Uniform Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of KS test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Uniform.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of KS test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```



### Utility of JB test---Normal Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Standard.Normal.JB, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of JB test ... Normal Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of JB test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Standard.Normal.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of JB test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```



### Utility of JB test---t Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$t.JB, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of JB test ... t Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of JB test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$t.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of JB test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```


### Utility of JB test---Uniform Distributions
```{r}

## add extra space to right margin of plot within frame
par(mar = c(7.1, 4.1, 3.1, 6.5), xpd = TRUE)
plot(nvec, data_powertest$Uniform.JB, axes=FALSE, ylim=c(0,1), xlab="", ylab="", 
   type="o", lwd = 2, col="black", main="Utility of JB test ... Uniform Samples")
axis(2, ylim=c(0,1),col="black",las=1)  
mtext("Power of JB test",side=2,line=2.5)
box()
par(new=TRUE)

## Plot the second plot and put axis scale on right
plot(nvec, data_error$Uniform.0.05,  xlab="", ylab="", ylim=c(-0.01,0.02),
    axes=FALSE, type="l", lty = 2, lwd = 2, col="red")
mtext("Inflation of Type I error rate in t test",side=4,col="black",line=4) 
axis(4, ylim=c(0,0.5), col="red",col.axis="black",las=1)
## a little farther out (line=4) to make room for labels
axis(4, ylim=c(0,0.2), col="blue",col.axis="blue",las=1)

## Draw the time axis
axis(1,pretty(range(nvec),10))
mtext("Sample Size",side=1,col="black",line=2.5)  
## Add Legend
legend("bottom", inset = c(0, -0.5), legend=c("power of JB test","Inflation of Type I error"),
  col=c("black","red"), lty = c(1, 2), horiz = TRUE)
```