---
title: "Utility of Normality Test in Two Samples Test"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10)
```

### Two Sample Case

```{r}
rm(list = ls())
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/TwoSampleCompareTestMethods.RData")
# Power of t-test
Power_ttest <-data.frame(power_t_table)
# Power of Wilcoxon test:
Powerwilcoxtest <-data.frame(power_wilcox_table)
# Power of t_test/wilcoxon test:
Powert_wilcoxtest <-data.frame(power_t_wilcox_table)
# Power of the permutation test:
PowerPermtest <-data.frame(power_perm_table)

# Computation time for t-test 
compTime_ttest <-data.frame(time_t_table)
# Computation time for wilcoxon test
CompTimewilcoxtest <-data.frame(time_wilcox_table)
# Computation time for wilcoxon/ttest
compTime_t_wilcoxtest <-data.frame(time_t_wilcox_table)
# Computation time for permutation test (minutes):
CompTimepermtest <-data.frame(time_perm_table)

```

#### Power of t-test/Mann-Whitney U test vs. permutation test
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, Power_ttest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, Powerwilcoxtest$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, Power_ttest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, Powerwilcoxtest$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttes", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")


plot(sample_sizes, Power_ttest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
    ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, Powerwilcoxtest$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi.Square Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, Power_ttest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
   ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, Powerwilcoxtest$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```


### Probability of Type I error rates
```{r}
rm(list = ls())
load("/Users/benedictkongyir/Downloads/TwoSampleCompareTestMethods_error.RData")
# Power of t-test
error_ttest <-data.frame(error_t_table)
# Power of Wilcoxon test:
error_wilcoxtest <-data.frame(error_wilcox_table)
# Power of t_test/wilcoxon test:
error_t_wilcoxtest <-data.frame(error_t_wilcox_table)
# Power of the permutation test:
error_Permtest <-data.frame(error_perm_table)

# Computation time for t-test 
compTime_ttest <-data.frame(time_t_table)
# Computation time for wilcoxon test
CompTimewilcoxtest <-data.frame(time_wilcox_table)
# Computation time for wilcoxon/ttest
compTime_t_wilcoxtest <-data.frame(time_t_wilcox_table)
# Computation time for permutation test (minutes):
CompTimepermtest <-data.frame(time_perm_table)

```

#### Power of t-test/Mann-Whitney U test vs. permutation test
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, error_ttest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, error_ttest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttes", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")


plot(sample_sizes, error_ttest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
    ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Chi.Square Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, error_ttest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
   ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```







```{r}
# Two Sample Case Type I error Rates
rm(list = ls())
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/TwoSampleTwoStage_vs_Permutation_TypeI_error.RData")
# Power of the t-test/Mann-Whitney U test:
errorTest <-data.frame(Error_t_wilcox_table)
# Power of the permutation test:
errorPerm <-data.frame(Error_perm_table)
# Computation time for t-test/Mann-Whitney U test (minutes):
compTime <-data.frame(time_t_wilcox_table)

# Computation time for permutation test (minutes):
CompTimePerm <-data.frame(time_perm_table)

```


```{r}
## Probability of Type I error rate: t-test/Mann-Whitney U test vs. permutation test
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, errorTest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, errorPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
abline(h = 0.05)
title(main = "Exponential Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

plot(sample_sizes, errorTest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, errorPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
abline(h = 0.05)
title(main = "Lognormal Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")


plot(sample_sizes, errorTest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, errorPerm$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
abline(h = 0.05)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

plot(sample_sizes, errorTest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 0.1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, errorPerm$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
abline(h = 0.05)
title(main = "Normal Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

```




```{r}

# One Sample Case Power
## t-test/Mann-Whitney U test vs. permutation test
rm(list = ls())
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPUTION TIME/OneSampleTwoStage_vs_Permutation.RData")
#load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/OneSampleTwoStage_vs_Permutation.RData")
# Power of the t-test/Mann-Whitney U test:
PowerTest <-data.frame(power_t_wilcox_table)
# Power of the permutation test:
PowerPerm <-data.frame(power_perm_table)
# Computation time for t-test/Mann-Whitney U test (minutes):
compTime <-data.frame(time_t_wilcox_table)

# Computation time for permutation test (minutes):
CompTimePerm <-data.frame(time_perm_table)

```

### Power:t-test/Mann-Whitney U test vs. permutation test
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, PowerTest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, PowerPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

plot(sample_sizes, PowerTest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, PowerPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
title(main = "Lognormal Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")


plot(sample_sizes, PowerTest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, PowerPerm$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

plot(sample_sizes, PowerTest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3,
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, PowerPerm$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
title(main = "Normal Samples")
legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

```

```{r}
rm(list = ls())
#load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/OneSampleCompareTestMethods.RData")
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/CompareTestMethods/OneSampleCompareTestMethods_power.RData")

# Power of t-test
Power_ttest <-data.frame(power_t_table)
# Power of Wilcoxon test:
Powerwilcoxtest <-data.frame(power_wilcox_table)
# Power of t_test/wilcoxon test:
Powert_wilcoxtest <-data.frame(power_t_wilcox_table)
# Power of the permutation test:
PowerPermtest <-data.frame(power_perm_table)

# Computation time for t-test 
compTime_ttest <-data.frame(time_t_table)
# Computation time for wilcoxon test
CompTimewilcoxtest <-data.frame(time_wilcox_table)
# Computation time for wilcoxon/ttest
compTime_ttest <-data.frame(time_t_wilcox_table)
# Computation time for permutation test (minutes):
CompTimewilcoxtest <-data.frame(time_perm_table)

```

#### Power of t-test/Mann-Whitney U test vs. permutation test
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, Power_ttest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Type I error")
lines(sample_sizes, Powerwilcoxtest$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, Power_ttest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Type I error")
lines(sample_sizes, Powerwilcoxtest$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttes", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")


plot(sample_sizes, Power_ttest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
    ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Type I error")
lines(sample_sizes, Powerwilcoxtest$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi.Square Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, Power_ttest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
   ylim = c(0, 1), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Type I error")
lines(sample_sizes, Powerwilcoxtest$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, Powert_wilcoxtest$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, PowerPermtest$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```




```{r}
# rm(list = ls())
# load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/OneSampleTwoStage_vs_Permutation_TypeI_error.RData")
# # Power of the t-test/Mann-Whitney U test:
# errorTest <-data.frame(Error_t_wilcox_table)
# # Power of the permutation test:
# errorPerm <-data.frame(Error_perm_table)
# # Computation time for t-test/Mann-Whitney U test (minutes):
# compTime <-data.frame(time_t_wilcox_table)
# 
# # Computation time for permutation test (minutes):
# CompTimePerm <-data.frame(time_perm_table)

```



```{r}
### Probability of ype I error rates: t-test/Mann-Whitney U test vs. permutation test
# #par(mar = c(9, 4, 4, 1), xpd = TRUE)
# par(mfrow = c(2,2))
# # Adjust margins to reduce space between plots
# par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
# plot(sample_sizes, errorTest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
#      ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
# lines(sample_sizes, errorPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
# abline(h = 0.05)
# title(main = "Exponential Samples")
# legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
#        col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")
# 
# plot(sample_sizes, errorTest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
#      ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
# lines(sample_sizes, errorPerm$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
# abline(h = 0.05)
# title(main = "Lognormal Samples")
# legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
#        col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")
# 
# 
# plot(sample_sizes, errorTest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
#      ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
# lines(sample_sizes, errorPerm$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
# abline(h = 0.05)
# title(main = "Chi-Squared Samples")
# legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
#        col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")
# 
# plot(sample_sizes, errorTest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
#      ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
# lines(sample_sizes, errorPerm$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
# abline(h = 0.05)
# title(main = "Normal Samples")
# legend("bottomright", legend=c("Wilcoxon/t", "Permutation"), lwd = 3,
#        col=c("red", "blue", "green",  "orange"), lty = 1:2, pch =1:2, cex = 0.8, title = "Test Method")

```


### Probability of Type I error rates
```{r}
rm(list = ls())
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Old stuff/COMPARISON OF DOWNSTREAM TEST METHODS/CompareTestMethods/OneampleCompareTestMethods_error.RData")
# Power of t-test
error_ttest <-data.frame(error_t_table)
# Power of Wilcoxon test:
error_wilcoxtest <-data.frame(error_wilcox_table)
# Power of t_test/wilcoxon test:
error_t_wilcoxtest <-data.frame(error_t_wilcox_table)
# Power of the permutation test:
error_Permtest <-data.frame(error_perm_table)

# Computation time for t-test 
compTime_ttest <-data.frame(time_t_table)
# Computation time for wilcoxon test
CompTimewilcoxtest <-data.frame(time_wilcox_table)
# Computation time for wilcoxon/ttest
compTime_t_wilcoxtest <-data.frame(time_t_wilcox_table)
# Computation time for permutation test (minutes):
CompTimepermtest <-data.frame(time_perm_table)

```

#### Power of t-test/Mann-Whitney U test vs. permutation test
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(sample_sizes, error_ttest$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Exponential Samples")
legend("topleft", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, error_ttest$LogNormal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
     ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "LogNormal Samples")
legend("topleft", legend=c("t","Wilcoxon", "Wilcoxon/ttes", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")


plot(sample_sizes, error_ttest$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
    ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Chi.Square Samples")
legend("topleft", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(sample_sizes, error_ttest$Standard.Normal, type = "o", lty = 1, pch = 1, col = "red", lwd = 3, 
   ylim = c(0, 0.5), xlim = range(sample_sizes), xlab = "Sample Size", ylab = "Power")
lines(sample_sizes, error_wilcoxtest$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(sample_sizes, error_t_wilcoxtest$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(sample_sizes, error_Permtest$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(h = 0.05)
title(main = "Standard.Normal Samples")
legend("topleft", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```

