---
title: "Power and Type I error of Two Sample t test"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
setwd("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Power Loss under Permutation Method/Rscript")
N <- 1e2; alpha <- 0.05; d <- 0.5; P= 1e2
sample_size <- c(10,20,30,40,50)
set.seed(33)
```

```{r}
# t test method
power_t_test_normal <- power_t_test_exp <- power_t_test_t <- power_t_test_chisq  <- 
power_t_test_gamma <- power_t_test_weibul <- power_t_test_logn<- numeric(length(sample_size))
for( k in 1 : length(sample_size)){
  n <- sample_size[k]
  print(n)
  
  pval_norm <- pval_exp <- pval_t <- pval_chisq <- pval_gamma <- pval_weibul <- pval_logn<- numeric(N)
  
  for(j in 1 : N){
    
    # ==========================================================================
    # x ~N(mu, sigma) 
    # ==========================================================================
    data_norm <- rnorm(n, mean = 0, sd = 1) + d
    pval_norm[j] <- t.test(data_norm)$p.value
    
    # ==========================================================================
    # e ~exp(theta),  E(X) = theta and VAR(X) = theta^2
    # ==========================================================================
    data_exp <- rexp(n, rate = 1) -1 + d
    pval_exp[j] <- t.test(data_exp)$p.value
    
    # ==========================================================================
    # t1 ~t_v,  E(X) = 0 for v >1 and VAR(X) = v/(v-2)
    # ==========================================================================
    data_t <-rt(n, df = 3)/sqrt(3) + d
    pval_t[j] <- t.test(data_t)$p.value
    
    # ==========================================================================
    # k1 ~X_k,  E(X) = k and VAR(X) = 2k
    # ==========================================================================
    data_chisq <-(rchisq(n, df = 3) - 3)/sqrt(6) + d
    pval_chisq[j] <- t.test(data_chisq)$p.value
    
    # ==========================================================================
    # g1 ~gamma(alpha, beta), where beta = 1/theta so E(X) = alpha/theta and 
    # VAR(X) = alpha/(theta)^2
    # ==========================================================================
    data_gamma <- (rgamma(n, shape = 3, rate = 0.1) -300)/sqrt(300) + d
    pval_gamma[j] <- t.test(data_gamma)$p.value
    
    # ==========================================================================
    # w1 ~Weibull(shape, scale)  E(X) = scale * Gamma(1 + 1/shape) and 
    # VAR(X) = scale^2[Gamma(1 + 2/shape) - (Gamma(1 + 1/shape))^2]
    # ==========================================================================
    data_weibul <- (rweibull(n, shape = 1, scale = 2) -2*gamma(51/50))/sqrt(4*(gamma(3) - gamma(2))) + d
    pval_weibul[j] <- t.test(data_weibul)$p.value  
    
    # ==========================================================================
    # l1 ~lognormal(mu, sigma^2)  E(X) = exp(mu + sigma^2/2) 
    # VAR(X) = [exp(sigma^2)-1]exp(2mu + sigma^2)
    # ==========================================================================
    data_logn <- (rlnorm(n, meanlog = 0, sdlog = 1) - exp(0 + 1/2))/sqrt((exp(1)-1)*exp(2*0 + 1)) + d
    pval_logn[j] <- t.test(data_logn)$p.value
    
  }
  # Power of t test
  power_t_test_normal[k] <- round(mean(pval_norm < alpha), 3)
  power_t_test_exp[k] <- round(mean(pval_exp < alpha), 3)
  power_t_test_t[k] <- round(mean(pval_t < alpha), 3)
  power_t_test_chisq[k] <- round(mean(pval_chisq < alpha), 3)
  power_t_test_gamma[k] <- round(mean(pval_gamma < alpha), 3)
  power_t_test_weibul[k] <- round(mean(pval_weibul < alpha), 3)
  power_t_test_logn[k] <- round(mean(pval_logn < alpha), 3)
  
}
```


```{r}

# Function to calculate the test statistic (difference of means)
calculate_test_statistic <- function(x) {
  return(mean(x) /sqrt(var(x)/length(x)))
}

# Permutation test approach
power_perm_test_norm <- power_perm_test_exp <- power_perm_test_t <- power_perm_test_chisq <- 
power_perm_test_gamma <- power_perm_test_weibul <- power_perm_test_logn<- numeric(length(sample_size))

for(k in 1 : length(sample_size)){
  n <- sample_size[k]
  print(n)
  pval_perm_norm <- pval_perm_exp <- pval_perm_t <- pval_perm_logn <- pval_perm_chisq <- 
    pval_perm_gamma <- pval_perm_weibul<- numeric(N)
  for(j in 1 : N){
    # generate data
    data_norm <- rnorm(n, mean = 0, sd = 1) + d
    data_exp <- rexp(n, rate = 1) -1 + d
    data_t <-rt(n, df = 3)/sqrt(3) + d
    data_chisq <-(rchisq(n, df = 3) - 3)/sqrt(6) + d
    data_gamma <- (rgamma(n, shape = 3, rate = 0.1) -300)/sqrt(300) + d
    data_weibul <- (rweibull(n, shape = 1, scale = 2) -2*gamma(51/50))/sqrt(4*(gamma(3) - gamma(2))) + d
    data_logn <- (rlnorm(n, meanlog = 0, sdlog = 1) - exp(0 + 1/2))/sqrt((exp(1)-1)*exp(2*0 + 1)) + d
    # Observed test statistic
    observed_statistic_norm <- calculate_test_statistic(data_norm)
    observed_statistic_exp <- calculate_test_statistic(data_exp)
    observed_statistic_t <- calculate_test_statistic(data_t)
    observed_statistic_chisq <- calculate_test_statistic(data_chisq)
    observed_statistic_gamma <- calculate_test_statistic(data_gamma)
    observed_statistic_weibul <- calculate_test_statistic(data_weibul)
    observed_statistic_logn <- calculate_test_statistic(data_logn)
    
    permuted_statistics_norm <- permuted_statistics_exp <- permuted_statistics_t <-permuted_statistics_logn <- 
      permuted_statistics_chisq <- permuted_statistics_gamma <- permuted_statistics_weibul<- rep(0, P)
    
    for(i in 1 : P){
      
      myIndex <- sample(c(-1, 1), n, replace = TRUE)  
      sample_data_norm <- myIndex * abs(data_norm)
      sample_data_exp <- myIndex * abs(data_exp)
      sample_data_t <- myIndex * abs(data_t)
      sample_data_chisq <- myIndex * abs(data_chisq)
      sample_data_gamma <- myIndex * abs(data_gamma)
      sample_data_weibul <- myIndex * abs(data_weibul)
      sample_data_logn <- myIndex * abs(data_logn)
  
      permuted_statistics_norm[i] <- calculate_test_statistic(sample_data_norm)
      permuted_statistics_exp[i] <- calculate_test_statistic(sample_data_exp)
      permuted_statistics_t[i] <- calculate_test_statistic(sample_data_t)
      permuted_statistics_chisq[i] <- calculate_test_statistic(sample_data_chisq)
      permuted_statistics_gamma[i] <- calculate_test_statistic(sample_data_gamma)
      permuted_statistics_weibul[i] <- calculate_test_statistic(sample_data_weibul)
      permuted_statistics_logn[i] <- calculate_test_statistic(sample_data_logn)
      
    }
    # Calculate the pvalue of test
    pval_perm_norm[j] <- round(mean(abs(permuted_statistics_norm) >= abs(observed_statistic_norm)), 5)
    pval_perm_exp[j] <- round(mean(abs(permuted_statistics_exp) >= abs(observed_statistic_exp)), 5)
    pval_perm_t[j] <- round(mean(abs(permuted_statistics_t) >= abs(observed_statistic_t)), 5)
    pval_perm_chisq[j] <- round(mean(abs(permuted_statistics_chisq) >= abs(observed_statistic_chisq)), 5)
    pval_perm_gamma[j] <- round(mean(abs(permuted_statistics_gamma) >= abs(observed_statistic_gamma)), 5)
    pval_perm_weibul[j] <- round(mean(abs(permuted_statistics_weibul) >= abs(observed_statistic_weibul)), 5)
    pval_perm_logn[j] <- round(mean(abs(permuted_statistics_logn) >= abs(observed_statistic_logn)), 5)
    
  }
  
  power_perm_test_norm[k] <- round(mean(pval_perm_norm < alpha), 5)
  power_perm_test_exp[k] <- round(mean(pval_perm_exp < alpha), 5)
  power_perm_test_t[k] <- round(mean(pval_perm_t < alpha), 5)
  power_perm_test_chisq[k] <- round(mean(pval_perm_chisq < alpha), 5)
  power_perm_test_gamma[k] <- round(mean(pval_perm_gamma < alpha), 5)
  power_perm_test_weibul[k] <- round(mean(pval_perm_weibul < alpha), 5)
  power_perm_test_logn[k] <- round(mean(pval_perm_logn < alpha), 5)
}
#powerloss
powerloss_norm <- power_perm_test_norm - power_t_test_normal
powerloss_exp <- power_perm_test_exp - power_t_test_exp
powerloss_t <- power_perm_test_t - power_t_test_t
powerloss_chisq <- power_perm_test_chisq - power_t_test_chisq
powerloss_gamma <- power_perm_test_gamma - power_t_test_gamma
powerloss_weibul <- power_perm_test_weibul - power_t_test_weibul
powerloss_logn <- power_perm_test_logn - power_t_test_logn

```


### Power under t test
```{r}

# power under t test
power_t<-c(power_t_test_normal, power_t_test_exp, power_t_test_t, power_t_test_chisq, power_t_test_weibul, power_t_test_logn)
power_table_t<-array(power_t, dim = c(5, 6), dimnames = list(sample_size,c("norm_t", "exp_t", "t distn_t","chisq",  "Weibull", "Lognormal")))
power_table_t

```


### Power under permutation test
```{r}
# power under permutation test
power_perm<-c(power_perm_test_norm, power_perm_test_exp, power_perm_test_t,  power_perm_test_chisq,  power_perm_test_weibul, power_perm_test_logn)
power_table_perm<-array(power_perm, dim = c(5, 6), dimnames = list(sample_size, c("Normal", "exp_perm", "t_perm", "chisq", "Weibull", "Lognormal")))
power_table_perm

```

### Power loss
```{r}
# power loss
powerloss_data<-c(powerloss_norm, powerloss_exp,powerloss_t, powerloss_chisq, powerloss_weibul, powerloss_logn)
powerloss_table<-array(powerloss_data, dim = c(5, 6), dimnames = list(sample_size, c("Normal", "exp_perm", "t_perm", "chisq",  "Weibull", "Lognormal")))
powerloss_table

```

```{r}

save.image(paste0("OneSample_result",".RData"))

```


