---
title: "Power loss of by permutation test approach"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

alpha <- 0.05; N= 1e5; d = 0.5
set.seed(2024)

```

```{r}
n.vec = c(10, 20, 30, 40, 50)

n.pwer.t.test <- e.pwer.t.test <- t.pwer.t.test <- logn.pwer.t.test <-gamma.pwer.t.test <- n.perm.test_power <- 
  e.perm.test_power <-t.perm.test_power <- logn.perm.test_power <- gamma.perm.test_power <- numeric(length(n.vec))
for(k in 1 : length(n.vec)){
  n = n.vec[k]
  powr_ttest_n <-powr_ttest_e <- powr_ttest_t <- powr_ttest_logn <- powr_ttest_gamma <- numeric(N)
    for(j in 1 : N){
      # normal distn
      n1 <- rnorm(n, mean = 0, sd = 1)
      n2 <- rnorm(n, mean = 0, sd = 1) + d
      if(t.test(n1, n2)$p.value < alpha){
        powr_ttest_n[j] <- 1
      }
      # =====================================================================
      # e ~exp(theta),  E(X) = theta and VAR(X) = theta^2
      # =====================================================================
      e1 <- rexp(n, rate = 1)
      e2 <- rexp(n, rate = 1) + d
      if(t.test(e1, e2)$p.value < alpha){
        powr_ttest_e[j] <- 1
      }
      # ======================================================================
      # t1 ~t_v,  E(X) = 0 for v >1 and VAR(X) = v/(v-2)
      # ======================================================================
      t1 <-rt(n, df = 3) 
      t2 <-rt(n, df = 3) 
      if(t.test((t1)/sqrt(3), (t2)/sqrt(3) + d)$p.value <= alpha){
        powr_ttest_t[j] <- 1
      }
      
      # ===================================================================================================
    # l1 ~lognormal(mu, sigma^2)  E(X) = exp(mu + sigma^2/2) VAR(X) = [exp(sigma^2)-1]exp(2mu + sigma^2)
    # ===================================================================================================
    l1 <- rlnorm(n, meanlog = 0, sdlog = 1)
    l2 <- rlnorm(n, meanlog = 0, sdlog = 1)
  
    z1 <- (l1- exp(0+1/2))/sqrt(sqrt((exp(1)-1)*exp(2*0 + 1)))
    z2 <- (l2- exp(0+1/2))/sqrt(sqrt((exp(1)-1)*exp(2*0 + 1)))
    if(t.test(z1, z2 + d)$p.value <= alpha){
      powr_ttest_logn[j] <- 1
    }
    
    # ===============================================================================================
    # g1 ~gamma(alpha, beta), where beta = 1/theta so E(X) = alpha/theta and VAR(X) = alpha/(theta)^2
    # ===============================================================================================
    g1 <- rgamma(n, shape = 3, rate = 0.1) 
    g2 <- rgamma(n, shape = 3, rate = 0.1)
    
    
    if(t.test((g1-30)/sqrt(300), (g2-30)/sqrt(300) + d)$p.value <= alpha){
      powr_ttest_gamma[j] <- 1
    }
    
    
    }
n.pwer.t.test[k] <-round(mean(powr_ttest_n),3)
e.pwer.t.test[k] <-round(mean(powr_ttest_e),3)
t.pwer.t.test[k] <-round(mean(powr_ttest_t),3)
logn.pwer.t.test[k] <-round(mean(powr_ttest_logn),3)
gamma.pwer.t.test[k] <-round(mean(powr_ttest_gamma),3)
# Function to calculate the test statistic (difference of means)
calculate_test_statistic <- function(x, y) {
  return(mean(x) - mean(y))
}
# Observed test statistic
n.observed_statistic <- calculate_test_statistic(n1, n2)
e.observed_statistic <- calculate_test_statistic(e1, e2)
t.observed_statistic <- calculate_test_statistic(t1, t2)
logn.observed_statistic <- calculate_test_statistic(z1, z2)
gamma.observed_statistic <- calculate_test_statistic(g1, g2)

n.permuted_statistics <- e.permuted_statistics <- t.permuted_statistics <- logn.permuted_statistics <- gamma.permuted_statistics<- numeric(N)
for (i in 1:N) {
  # Randomly permute the trt labels
  #normal
  permuted_data <- c(n1, n2)
  permuted_data <- sample(permuted_data)
  # Calculate the test statistic for the permuted data
  permuted_n1 <- permuted_data[1:length(n1)]
  permuted_n2 <- permuted_data[(length(n1) + 1):(length(n1) + length(n2))]
  n.permuted_statistics[i] <- calculate_test_statistic(permuted_n1, permuted_n2)
  # exponential
  permuted_data <- c(e1, e2)
  permuted_data <- sample(permuted_data)
  permuted_e1 <- permuted_data[1:length(e1)]
  permuted_e2 <- permuted_data[(length(e1) + 1):(length(e1) + length(e2))]
  e.permuted_statistics[i] <- calculate_test_statistic(permuted_e1, permuted_e2)
  
  # t
  permuted_data <- c(t1, t2)
  permuted_data <- sample(permuted_data)
  permuted_t1 <- permuted_data[1:length(t1)]
  permuted_t2 <- permuted_data[(length(t1) + 1):(length(t1) + length(t2))]
  t.permuted_statistics[i] <- calculate_test_statistic(permuted_t1, permuted_t2)
  
  # lognormal
  permuted_data <- c(z1, z2)
  permuted_data <- sample(permuted_data)
  permuted_z1 <- permuted_data[1:length(z1)]
  permuted_z2 <- permuted_data[(length(z1) + 1):(length(z1) + length(z2))]
  logn.permuted_statistics[i] <- calculate_test_statistic(permuted_z1, permuted_z2)
  
  # gamma
  permuted_data <- c(g1, g2)
  permuted_data <- sample(permuted_data)
  permuted_g1 <- permuted_data[1:length(g1)]
  permuted_g2 <- permuted_data[(length(g1) + 1):(length(g1) + length(g2))]
  gamma.permuted_statistics[i] <- calculate_test_statistic(permuted_g1, permuted_g2)
  
}
# Calculate the power of test
n.perm.test_power[k] <- 1- round(mean(abs(n.permuted_statistics) >= abs(n.observed_statistic)), 3)
e.perm.test_power[k] <- 1- round(mean(abs(e.permuted_statistics) >= abs(e.observed_statistic)), 3)
t.perm.test_power[k] <- 1- round(mean(abs(t.permuted_statistics) >= abs(t.observed_statistic)), 3)
logn.perm.test_power[k] <- 1- round(mean(abs(logn.permuted_statistics) >= abs(logn.observed_statistic)), 3)
gamma.perm.test_power[k] <- 1- round(mean(abs(gamma.permuted_statistics) >= abs(gamma.observed_statistic)), 3)
}

n.pwloss <- n.perm.test_power - n.pwer.t.test
e.pwloss <- e.perm.test_power - e.pwer.t.test
t.pwloss <- t.perm.test_power - t.pwer.t.test
logn.pwloss <- logn.perm.test_power - logn.pwer.t.test
gamma.pwloss <- gamma.perm.test_power - gamma.pwer.t.test
```

### Power under t test
```{r}
# power under t test
power_t<-c(n.pwer.t.test, e.pwer.t.test, t.pwer.t.test,  logn.pwer.t.test, gamma.pwer.t.test)
power_table_t<-array(power_t, dim = c(5, 5), dimnames = list(n.vec,
      c("norm_t", "exp_t", "t distn_t", "lognormal_t", "gamma_t")))
power_table_t

```

### Power under permutation test
```{r}
# power under t test
power_perm<-c(n.perm.test_power, e.perm.test_power, t.perm.test_power,  logn.perm.test_power, gamma.perm.test_power)
power_table_perm<-array(power_perm, dim = c(5, 5), dimnames = list(n.vec,
      c("norm_perm", "exp_perm", "t_perm",  "lognormal_perm", "gamma_perm")))
power_table_perm

```


### Power loss under permutation test
```{r}
# power loss
powerloss_data<-c(n.pwloss,e.pwloss, t.pwloss,logn.pwloss, gamma.pwloss)
powerloss_table<-array(powerloss_data, dim = c(5, 5), dimnames = list(n.vec,
      c("normal", "exponential", "t distn", "lognormal", "gamma")))
powerloss_table

```



```{r}
save.image(paste0("powerloss_perm.test",".RData"))
```

