---
title: "Utility of Normality Test in Two Samples Test"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10)
# Load necessary packages
library(knitr)
library(kableExtra)
```


```{r}
rm(list = ls())
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/AREA UNDER CURVE/POWER/OneSamplepowerAUC.RData")
```


### Two Sample Case

```{r}
# Power
# Power of sw-test
power_sw_test <-data.frame(power_sw)
# Power of t test:
power_t_test <-data.frame(power_t)
# Power of wilcon-test
power_wilcox_test <-data.frame(power_wilcox)
# Power of t/wilcoxon test:
power_t_wilcox_test <-data.frame(power_t_wilcox)
# Power of perm test:
power_perm_test <-data.frame(power_perm)

# Type I error
# Power of t test:
error_t_test <-data.frame(error_t)
# Power of wilcon-test
error_wilcox_test <-data.frame(error_wilcox)
# Power of t/wilcoxon test:
error_t_wilcox_test <-data.frame(error_t_wilcox)
# Power of perm test:
error_perm_test <-data.frame(error_perm)

# Computation time for t-test 
time_t <-data.frame(avg_time_t)
# Computation time for wilcoxon test
time_wilcox <-data.frame(avg_time_wilcox)
# Computation time for wilcoxon/ttest
time_t_wilcox <-data.frame(avg_time_t_wilcox)
# Computation time for permutation test (minutes):
time_perm <-data.frame(avg_time_perm)
```



#### One Sample Power of downstream tests
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(nvec, power_t_test$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$LogNormal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$Standard.Normal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```

#### One Sample Type I error of downstream tests
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(nvec, error_t_test$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Power of SW test", ylim = c(0, 0.5))
lines(nvec, error_wilcox_test$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Power of SW test", ylim = c(0, 0.5))
lines(nvec, error_wilcox_test$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$LogNormal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Power of SW test", ylim = c(0, 0.5))
lines(nvec, error_wilcox_test$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$Standard.Normal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Power of SW test", ylim = c(0, 0.5))
lines(nvec, error_wilcox_test$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```
```{r}
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/AREA UNDER CURVE/POWER/TwoSamplepowerAUC.RData")
```

```{r}
# Power
# Power of sw-test
power_sw_test <-data.frame(power_sw)
# Power of t test:
power_t_test <-data.frame(power_t)
# Power of wilcon-test
power_wilcox_test <-data.frame(power_wilcox)
# Power of t/wilcoxon test:
power_t_wilcox_test <-data.frame(power_t_wilcox)
# Power of perm test:
power_perm_test <-data.frame(power_perm)

# Type I error
# Power of t test:
error_t_test <-data.frame(error_t)
# Power of wilcon-test
error_wilcox_test <-data.frame(error_wilcox)
# Power of t/wilcoxon test:
error_t_wilcox_test <-data.frame(error_t_wilcox)
# Power of perm test:
error_perm_test <-data.frame(error_perm)


```

### plot only Lognormal
```{r, fig.height= 8, fig.width=10}
plot(nvec, power_t_test$LogNormal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,ylim = c(0, 1),  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
abline(v = c(8, 50), col = "grey")
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Permutation"), lwd = 3,
       col=c("red", "blue",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")
```


#### Two Sample Power of downstream tests
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(nvec, power_t_test$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, ylim = c(0, 1),  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3, ylim = c(0, 1),  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$LogNormal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,ylim = c(0, 1),  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, power_t_test$Standard.Normal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,ylim = c(0, 1),  xlab = "sample size", ylab = "Power of SW test")
lines(nvec, power_wilcox_test$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, power_t_wilcox_test$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, power_perm_test$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```

#### Two Sample Type I error of downstream tests
```{r}
#par(mar = c(9, 4, 4, 1), xpd = TRUE)
par(mfrow = c(2,2))
# Adjust margins to reduce space between plots
par(mai = c(0.75, 0.75, 0.2, 0.2))  # Adjust as needed
plot(nvec, error_t_test$Exponential,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Type I error Rate", ylim = c(0, 0.1))
lines(nvec, error_wilcox_test$Exponential, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Exponential, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Exponential, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Exponential Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$Chi.Square,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Type I error Rate", ylim = c(0, 0.1))
lines(nvec, error_wilcox_test$Chi.Square, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Chi.Square, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Chi.Square, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Chi-Squared Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$LogNormal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Type I error Rate", ylim = c(0, 0.1))
lines(nvec, error_wilcox_test$LogNormal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$LogNormal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$LogNormal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "LogNormal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

plot(nvec, error_t_test$Standard.Normal,  type = "o", lty = 1, pch = 1, col = "red", lwd = 3,  xlab = "Type I error", ylab = "Type I error Rate", ylim = c(0, 0.1))
lines(nvec, error_wilcox_test$Standard.Normal, type = "o", lty = 2, pch = 2, col = "blue", lwd = 3)
lines(nvec, error_t_wilcox_test$Standard.Normal, type = "o", lty = 3, pch = 3, col = "green", lwd = 3)
lines(nvec, error_perm_test$Standard.Normal, type = "o", lty = 4, pch = 4, col = "orange", lwd = 3)
title(main = "Standard.Normal Samples")
legend("bottomright", legend=c("t","Wilcoxon", "Wilcoxon/ttest", "Permutation"), lwd = 3,
       col=c("red", "blue", "green",  "orange"), lty = 1:4, pch =1:4, cex = 0.8, title = "Test Method")

```

