---
title: "Two Sample Type I error Rates"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 12, fig.width = 12, warning = FALSE, message = FALSE, verbose = FALSE)
# Load user-defined functions
setwd("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/SPRING2025/DOWNSTREAM TESTS/compare test methods_20250310/twosamples/twosamples")
source("~/Desktop/OSU/Research/Pretest-Simulation/functions/User_defined_functions.R")
source("~/Desktop/OSU/Research/Pretest-Simulation/functions/utility.R")
```



```{r}
save.image(file = "TypeI_error_two_sample_test.RData")
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/SPRING2025/DOWNSTREAM TESTS/compare test methods_20250310/twosamples/twosamples/TypeI_error_two_sample_test.RData")
plot_data <- data.frame(
  SampleSize = rep(sample_size, times = length(distribution) * 5),
  Distribution = rep(rep(distribution, each = length(sample_size)), times = 5),
  ErrorRate = c(as.vector(Type_I_error_t.test),
                as.vector(Type_I_error_perm.test),
                as.vector(Type_I_error_adaptive.test),
                as.vector(Type_I_error_conditional.test),
                as.vector(power_sw)),
  Test = rep(c("t-test",  "Permutation", "adaptive t/perm",
               "Conditional t-test", "Shapiro-Wilk"),
             each = length(sample_size) * length(distribution))
)

# Filter out Normal distribution
#plot_data <- subset(plot_data, Distribution != "Normal")

# Define PlotType for row-based faceting
plot_data$PlotType <- ifelse(
  plot_data$Test == "Shapiro-Wilk", "SW Power",
  ifelse(plot_data$Test == "Conditional t-test", "Conditional Type I Error", "Type I Error")
)

# Convert PlotType to factor for ordering rows
plot_data$PlotType <- factor(plot_data$PlotType, levels = c("SW Power", "Type I Error", "Conditional Type I Error"))

# --- Plot using facet_grid (rows = PlotType, columns = Distribution) ---
# Base plot
p <- ggplot(plot_data, aes(x = SampleSize, y = ErrorRate, color = Test, linetype = Test)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  facet_grid(PlotType ~ Distribution, scales = "free_y") +
  labs(
    title = "Type I Error Rates, Shapiro-Wilk Power, and Conditional Type I Error by Distribution",
    x = "Sample Size",
    y = "Rate / Power"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")

# Add 0.05 reference lines **only to Type I Error plots**
p <- p + geom_hline(
  data = subset(plot_data, PlotType == "Type I Error"),
  aes(yintercept = 0.05),
  linetype = "dashed",
  color = "gray40"
)

p
# Save plot
#ggsave("type1_error_sw_power_conditional_plot.png", p, width = 12, height = 10)

#save.image(paste0("twosample_test_v6_20250320",".RData"))

```


