---
title: "Density plots of two sample t test statistic"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
setwd("D:/Research_Fall2023/Pretest-Simulation/Power and Type I error Rate/Rmarkdown")
set.seed(2024)
N <- 1e5
alpha <- 0.05
n <- 10
```


```{r}
norm_statistic <- log_statistic <-t_statistic <- u_statistic<-e_statistic <- k_statistic <-g_statistic <- w_statistic <- NULL
 for(j in 1 : N){
   # normal distn
    n1 <- rnorm(n, mean = 0, sd = 1)
    n2 <- rnorm(n, mean = 0, sd = 1)
    
    norm_statistic[j] <- t.test(n1, n2)$statistic
    
    # ===============================================================================================
    # e ~exp(theta),  E(X) = theta and VAR(X) = theta^2
    # ===============================================================================================
    
    e1 <- rexp(n, rate = 1)
    e2 <- rexp(n, rate = 1)
    e_statistic[j] <- t.test(e1 - 1, e2 - 1)$statistic
    
    # ===============================================================================================
    # u1 ~U(a, b),  E(X) = (a + b)/2 and VAR(X) = [(b-a)^2]/12
    # ===============================================================================================
    u1 <- runif(n, min = 0, max = 1)
    u2 <- runif(n, min = 0, max = 1)
    
      u_statistic[j] <- t.test((u1-0.5)/sqrt(1/12),  (u2-0.5)/sqrt(1/12))$statistic
    
    # ===============================================================================================
    # t1 ~t_v,  E(X) = 0 for v >1 and VAR(X) = v/(v-2)
    # ===============================================================================================
    t1 <-rt(n, df = 3) 
    t2 <-rt(n, df = 3) 
    
     t_statistic[j] <- t.test((t1)/sqrt(3), (t2)/sqrt(3))$statistic
    
    # ===============================================================================================
    # k1 ~X_k,  E(X) = k and VAR(X) = 2k
    # ===============================================================================================
    k1 <-rchisq(n, df = 7) 
    k2 <-rchisq(n, df = 7) 
    
     k_statistic[j] <- t.test((k1 - 7)/sqrt(14), (k2 - 7)/sqrt(14))$statistic
    
    # ===============================================================================================
    # g1 ~gamma(alpha, beta), where beta = 1/theta so E(X) = alpha/theta and VAR(X) = alpha/(theta)^2
    # ===============================================================================================
    g1 <- rgamma(n, shape = 3, rate = 0.1) 
    g2 <- rgamma(n, shape = 3, rate = 0.1)
    
    g_statistic[j] <- t.test((g1-30)/sqrt(300), (g2-30)/sqrt(300))$statistic
    
    # ===============================================================================================
    # w1 ~Weibull(shape, scale)  E(X) = scale Gamma(1 + 1/shape) and 
    # VAR(X) = scale^2[Gamma(1 + 2/shape) - (Gamma(1 + 1/shape))^2]
    # ===============================================================================================
    w1 <- rweibull(n, shape = 1, scale = 2) 
    w2 <- rweibull(n, shape = 1, scale = 2)
    u <- (w1-2*gamma(2))/sqrt(4*(gamma(3) - gamma(2)))
    w <- (w2-2*gamma(2))/sqrt(4*(gamma(3) - gamma(2)))
    
    w_statistic[j] <- t.test(u, w)$statistic
      
    # ===================================================================================================
    # l1 ~lognormal(mu, sigma^2)  E(X) = exp(mu + sigma^2/2) VAR(X) = [exp(sigma^2)-1]exp(2mu + sigma^2)
    # ===================================================================================================
    l1 <- rlnorm(n, meanlog = 0, sdlog = 1)
    l2 <- rlnorm(n, meanlog = 0, sdlog = 1)
    z1 <- (l1- exp(0+1/2))/sqrt(sqrt((exp(1)-1)*exp(2*0 + 1)))
    z2 <- (l2- exp(0+1/2))/sqrt(sqrt((exp(1)-1)*exp(2*0 + 1)))
    
    log_statistic[j] <- t.test(z1, z2)$statistic
    
 }
  
```


```{r}
save.image(paste0("two_samples_plots",".RData"))
```


### density plots of test statistics


```{r}
df = 2*n - 2
z <- seq(from = -3, to = 3, by = 0.01)
#par(mar = c(5, 4, 4, 8), xpd = TRUE)
# normal Distribution
#hist(norm_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")
plot(z, dt(z, df = n-1), col = "red", type = "l", xlab = " ",  ylab = "Density",  lwd = 2, main = " ", sub = " ")
title(main = "Histogram of t test Statistics", sub = "normal Dist")
lines(density(norm_statistic), lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright",  legend=c("t density", "true density"),col=c( "red","black"), lty =1 ,cex = 0.5)

# Exponential Distribution
#hist(e_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")
plot(z, dt(z, df = n-1), col = "red",type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Exponential Dist")
lines(density(e_statistic) , lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

# t Distribution
#hist(t_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")
plot(z, dt(z, df = n-1), col = "red", type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "t Dist")
lines(density(t_statistic) , lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

# uniform Distribution
#hist(u_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")

plot(z, dt(z, df = n-1), col = "red",  type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Uniform Dist")
lines(density(u_statistic) , lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)


# chi-squared Distribution
#hist(k_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")

plot(z, dt(z, df = n-1), col = "red",  type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Chi-Square Dist")
lines(density(k_statistic) , lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df ), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

# weibull Distribution
#hist(w_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")

plot(z, dt(z, df = n-1), col = "red" , type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Weibull Dist")
lines(density(w_statistic) , lwd = 2)
abline(v=qt(0.025, df = df ), col = "blue")
abline(v=qt(0.975, df = df ), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

# gamma Distribution
#hist(g_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")
plot(z, dt(z, df = n-1), col = "red" , type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Gamma Dist")
lines(density(g_statistic) , lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

# lognormal Distribution
#hist(log_statistic, prob = T, ylim = c(0, 0.4), xlim = c(-8, 8), main = " ", sub = " ")

plot(z, dt(z, df = n-1), col = "red" , type = "l", lwd = 2, main = " ", sub = " " , xlab = " ",  ylab = "Density")
title(main = "Histogram of t test Statistics", sub = "Lognormal Dist")
lines(density(log_statistic), lwd = 2)
abline(v=qt(0.025, df = df), col = "blue")
abline(v=qt(0.975, df = df), col = "blue")
legend("topright", legend=c("t density", "true density"),col=c( "red","black"), lty =1,cex = 0.5)

```


```{r}
# Calculation of Type 1 error

#normal Distn
left_norm <- mean(norm_statistic < qt(0.025, df = df))
right_norm <- mean(norm_statistic > qt(0.975, df = df))
Type1_error_norm <- sum(left_norm + right_norm)

#exponential Distn
left_e <- mean(e_statistic < qt(0.025, df = df))
right_e <- mean(e_statistic > qt(0.975, df = df))
Type1_error_e <- sum(left_e + right_e)
#t Distn
left_t <- mean(t_statistic < qt(0.025, df = df))
right_t <- mean(t_statistic > qt(0.975, df = df))
Type1_error_t <- sum(left_t + right_t)
#uuniform Distn
left_u <- mean(u_statistic < qt(0.025, df = df))
right_u <- mean(u_statistic > qt(0.975, df = df))
Type1_error_u <- sum(left_u + right_u)
#Chi-Squared Distn
left_k <- mean(k_statistic < qt(0.025, df = df))
right_k <- mean(k_statistic > qt(0.975, df = df))
Type1_error_k <- sum(left_k + right_k)
#Weilbul Distn
left_w <- mean(w_statistic < qt(0.025, df = df))
right_w <- mean(w_statistic > qt(0.975, df = df))
Type1_error_w <- sum(left_w + right_w)
#Gamma Distn
left_g <- mean(g_statistic < qt(0.025, df = df))
right_g <- mean(g_statistic > qt(0.975, df = df))
Type1_error_g <- sum(left_g + right_g)
#Lognormal Distn
left_l <- mean(log_statistic < qt(0.025, df = df))
right_l <- mean(log_statistic > qt(0.975, df = df))
Type1_error_l <- sum(left_l + right_l)
```

### Estimated Type I errors

```{r}
# power of SW test
errors <-c( Type1_error_norm, Type1_error_e, Type1_error_t, Type1_error_u,Type1_error_k,Type1_error_w, Type1_error_g,Type1_error_l)
dist <-c("normal", "exponential", "t", "uniform", "chi-squared", "weillbul", "gamma", "lognormal")

# put data in a table
kk <- data.frame(dist, errors)
knitr::kable(kk, caption = "Estimated Type I errors")
```