---
title: "Power and Type I error Rate"
author: "Benedict Kongyir"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
rm(list = ls())
setwd("D:/OSU/Research_Fall2023")
set.seed(1)
N <- 100000
alpha <- 0.05
d <- 0.5
sample_size <- c(10,20,30,40,50,100)
```

```{r}
#power of SW test
Power_SW_exp <-Power_SW_unif <- Power_SW_t <- Power_SW_chisq <- Power_SW_gamma <- numeric(length(sample_size))
#Type I error
Type1Error_Norm <- Type1Error_exp <-Type1Error_unif <- Type1Error_t <- Type1Error_chisq <- Type1Error_gamma <- numeric(length(sample_size))
#inflation of Type I error
InflationType1Error_exp <-InflationType1Error_unif <- InflationType1Error_t <- InflationType1Error_chisq <- InflationType1Error_gamma <- numeric(length(sample_size))
#Power of t test
Power_ttest_Norm <- Power_ttest_exp <-Power_ttest_unif <- Power_ttest_t <- Power_ttest_chisq <- Power_ttest_gamma <- numeric(length(sample_size))
#powerloss
powrloss_exp <-powrloss_unif  <-powrloss_gamma <-powrloss_beta <-powrloss_chisq <-powrloss_t <- numeric(length(sample_size))

```

```{r}
for( i in 1 : length(sample_size)){
  n <- sample_size[i]
print(n)
PowrSW_exp <- PowrSW_unif <- PowrSW_t <- PowrSW_chisq <- PowrSW_gamma <- numeric(N)
error_ttest_norm <- error_ttest_exp <- error_ttest_unif <- error_ttest_t <- error_ttest_chisq <- error_ttest_gamma <- numeric(N)
powr_ttest_norm <- powr_ttest_exp <- powr_ttest_unif <- powr_ttest_t <- powr_ttest_chisq <- powr_ttest_gamma <- numeric(N)
 for(j in 1 : N){
   # normal distn
    n1 <- rnorm(n, mean = 0, sd = 1)
    n2 <- rnorm(n, mean = 0, sd = 1)
    if(t.test(n1, n2)$p.value <= alpha){
      error_ttest_norm[j] <- 1
    }
    if(t.test(n1, n2 + d)$p.value <= alpha){
      powr_ttest_norm[j] <- 1
    }
    # exponential distn
    e1 <- rexp(n, rate = 1)
    e2 <- rexp(n, rate = 1)
    if(t.test(e1, e2)$p.value <= alpha){
      error_ttest_exp[j] <- 1
    }
    if(shapiro.test(e1)$p.value <= alpha/2 | shapiro.test(e2)$p.value <= alpha/2){
      PowrSW_exp[j] <- 1
    }
    if(t.test(e1 -1, e2 - 1 + d)$p.value <= alpha){
      powr_ttest_exp[j] <- 1
    }
    # uniform distn
    u1 <- runif(n, min = 0, max = 1)
    u2 <- runif(n, min = 0, max = 1)
    if(t.test(u1, u2)$p.value <= alpha){
      error_ttest_unif[j] <- 1
    } 
    if(shapiro.test(u1)$p.value <= alpha/2 | shapiro.test(u2)$p.value <= alpha/2){
      PowrSW_unif[j] <- 1
    }
    if(t.test((u1-0.5)/sqrt(1/12), (u2-0.5)/sqrt(1/12) + d)$p.value <= alpha){
      powr_ttest_unif[j] <- 1
    }
    # t distn
    t1 <-rt(n, df = 3) 
    t2 <-rt(n, df = 3) 
    if(t.test(t1, t2)$p.value <= alpha){
      error_ttest_t[j] <- 1
    }
    if(shapiro.test(t1)$p.value <= alpha/2 | shapiro.test(t2)$p.value <= alpha/2){
      PowrSW_t[j] <- 1
    }
    if(t.test((t1 - 3)/sqrt(3), (t2 - 3)/sqrt(3) + d)$p.value <= alpha){
      powr_ttest_t[j] <- 1
    }
    
    # chisq distn
    k1 <-rchisq(n, df = 7) 
    k2 <-rchisq(n, df = 7) 
    if(t.test(k1, k2)$p.value <= alpha){
      error_ttest_chisq[j] <- 1
    }
    if(shapiro.test(k1)$p.value <= alpha/2 | shapiro.test(k2)$p.value <= alpha/2){
      PowrSW_chisq[j] <- 1
    }
    if(t.test((k1 - 7)/sqrt(14), (k2 - 7)/sqrt(14) + d)$p.value <= alpha){
      powr_ttest_chisq[j] <- 1
    }
    #gamma distn
    g1 <- rgamma(n, shape = 3, rate = 0.1) 
    g2 <- rgamma(n, shape = 3, rate = 0.1) 
    if(t.test(g1, g2)$p.value <= alpha){
      error_ttest_gamma[j] <- 1
    }# Type I error 
    if(shapiro.test(g1)$p.value <= alpha/2 | shapiro.test(g2)$p.value <= alpha/2){
      PowrSW_gamma[j] <- 1
    }#power of SW test
    if(t.test((g1-0.3)/sqrt(0.03), (g2-0.3)/sqrt(0.03) + d)$p.value <= alpha){
      powr_ttest_gamma[j] <- 1
    }#power of t test
 }
  #Type I error
  Type1Error_Norm[i] <- round(mean(error_ttest_norm), 3)
  Type1Error_exp[i] <- round(mean(error_ttest_exp), 3)
  Type1Error_unif[i] <- round(mean(error_ttest_unif), 3)
  Type1Error_t[i] <- round(mean(error_ttest_t), 3)
  Type1Error_chisq[i] <- round(mean(error_ttest_chisq), 3)
  Type1Error_gamma[i] <- round(mean(error_ttest_gamma), 3)
  #inflation of Type I error
  InflationType1Error_exp[i] <- Type1Error_exp[i] - Type1Error_Norm[i]
  InflationType1Error_unif[i] <- Type1Error_unif[i] - Type1Error_Norm[i]
  InflationType1Error_t[i] <- Type1Error_t[i] - Type1Error_Norm[i]
  InflationType1Error_chisq[i] <- Type1Error_chisq[i] - Type1Error_Norm[i]
  InflationType1Error_gamma[i] <- Type1Error_gamma[i] - Type1Error_Norm[i]
  
  #power of SW test
  Power_SW_exp[i] <- round(mean(PowrSW_exp), 3)
  Power_SW_unif[i] <- round(mean(PowrSW_unif), 3)
  Power_SW_t[i] <- round(mean(PowrSW_t), 3)
  Power_SW_chisq[i] <- round(mean(PowrSW_chisq), 3)
  Power_SW_gamma[i] <- round(mean(PowrSW_gamma), 3)
  # Power of t test
  Power_ttest_Norm[i] <- round(mean(powr_ttest_norm), 3)
  Power_ttest_exp[i] <- round(mean(powr_ttest_exp), 3)
  Power_ttest_unif[i] <- round(mean(powr_ttest_unif), 3)
  Power_ttest_t[i] <- round(mean(powr_ttest_t), 3)
  Power_ttest_chisq[i] <- round(mean(powr_ttest_chisq), 3)
  Power_ttest_gamma[i] <- round(mean(powr_ttest_gamma), 3)
  
  # Powerloss of t test
  powrloss_exp[i] <- Power_ttest_Norm[i] - Power_ttest_exp[i]
  powrloss_unif[i] <- Power_ttest_Norm[i] - Power_ttest_unif[i]
  powrloss_t[i] <- Power_ttest_Norm[i] - Power_ttest_t[i]
  powrloss_chisq[i] <- Power_ttest_Norm[i] - Power_ttest_chisq[i]
  powrloss_gamma[i] <- Power_ttest_Norm[i] - Power_ttest_gamma[i]
}
```

### power of SW test
```{r}
# power of SW test
data1 <-c(Power_SW_exp, Power_SW_unif, Power_SW_t,Power_SW_chisq,Power_SW_gamma)
Power_SW_test<-array(data1, dim = c(6, 5), dimnames = list(sample_size,c("exp", "unif", "t", "chisq", "gamma")))
Power_SW_test
```

### Type I error 

```{r}
# Type I error
data2 <-c(Type1Error_Norm, Type1Error_exp, Type1Error_unif, Type1Error_t, Type1Error_chisq,Type1Error_gamma )
Type1_error<-array(data2, dim = c(6, 6), dimnames = list(sample_size,c("norm", "exp", "unif", "t", "chisq", "gamma")))
Type1_error
```

### inflation of Type I error
```{r}
#inflation of Type I error
data5 <-c(InflationType1Error_exp, InflationType1Error_unif, InflationType1Error_t,InflationType1Error_chisq,InflationType1Error_gamma)
inflation_error<-array(data5, dim = c(6, 5), dimnames = list(sample_size,c("exp", "unif", "t", "chisq", "gamma")))
inflation_error
```

### power of t test
```{r}
# power of t test
data3 <-c(Power_ttest_Norm, Power_ttest_exp , Power_ttest_unif, Power_ttest_t, Power_ttest_chisq, Power_ttest_gamma )
Power_t_test<-array(data3, dim = c(6, 6), dimnames = list(sample_size,c("norm", "exp", "unif", "t", "chisq", "gamma")))
Power_t_test
```

### powerloss of t test
```{r}
#powerloss of t test
data4 <-c(powrloss_exp, powrloss_unif, powrloss_t, powrloss_chisq, powrloss_gamma)
Powerloss_t_test<-array(data4, dim = c(6, 5), dimnames = list(sample_size,c("exp", "unif", "t", "chisq", "gamma")))
Powerloss_t_test
```


```{r}
save.image(paste0("two_samples_results",".RData"))
```

```{r}
#power of SW test
plot(sample_size, Power_SW_exp, type="l", lwd= 2, col = "red", 
     ylim = c(0, 1),xlab = "Sample Size", ylab = "Power")
lines(sample_size, Power_SW_unif, lwd= 2, col = "blue")
lines(sample_size, Power_SW_t,lwd= 2, col = "purple")
lines(sample_size, Power_SW_chisq, lwd= 2,col = "green")
lines(sample_size, Power_SW_gamma, lwd= 2,col = "pink")
title(main = "Power SW test.")
legend("topleft", legend=c("exponential", "uniform", "t", "chisq", "gamma"),
       col=c("red","blue", "purple", "green", "pink"), lty =1,cex = 0.5)
```



```{r}
plot(sample_size, Type1Error_Norm, type="l", lwd= 2, col = "red", 
     ylim = c(0.03, 0.09),xlab = "Sample Size", ylab = "Type I error rate")
lines(sample_size, Type1Error_exp, lwd= 2, col = "blue")
lines(sample_size, Type1Error_unif,lwd= 2, col = "gold")
lines(sample_size, Type1Error_t,lwd= 2, col = "green")
lines(sample_size, Type1Error_chisq, col = "brown")
lines(sample_size, Type1Error_gamma, col = "pink")
abline(h = 0.05)
title(main = "Type I error of t test")
legend("topleft", legend=c("normal", "expontial", "uniform", "t", "chisq", "gamma"),
       col=c( "red","blue", "gold", "green", "brown", "pink", "violet"), lty =1,cex = 0.5)
```


```{r}
plot(sample_size, Power_ttest_Norm, type="l", lwd= 2, col = "red", 
     ylim = c(0, 1),xlab = "Sample Size", ylab = "Power")
lines(sample_size, Power_ttest_exp, lwd= 2, col = "blue")
lines(sample_size, Power_ttest_unif,lwd= 2, col = "gold")
lines(sample_size, Power_ttest_t,lwd= 2, col = "green")
lines(sample_size, Power_ttest_chisq, col = "brown")
lines(sample_size, Power_ttest_gamma, col = "pink")
title(main = "Power of t test")
legend("topleft", legend=c("normal", "expontial", "uniform", "t", "chisq", "gamma"),
       col=c( "red","blue", "gold", "green", "brown", "pink", "violet"), lty =1,cex = 0.5)
```






















