---
title: "Two Sample Type I error Rates"
author: "Benedict Kongyir"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 12, fig.width = 12, warning = FALSE, message = FALSE, verbose = FALSE)
# Load user-defined functions
setwd("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/SPRING2025/DOWNSTREAM TESTS/compare test methods_20250310/twosamples/twosamples")
source("~/Desktop/OSU/Research/Pretest-Simulation/functions/User_defined_functions.R")
source("~/Desktop/OSU/Research/Pretest-Simulation/functions/utility.R")
```


```{r}
# 
# # set up cores for parallel processing
# par_set <- function(cores_reserve = 2) {
#   cores <- parallel::detectCores()
#   cores_use <- max(1, cores - cores_reserve)
#   
#   cl <- parallel::makeCluster(cores_use, type = "SOCK")  
#   doSNOW::registerDoSNOW(cl)  
#   
#   foreach::getDoParWorkers()
#   return(cl)
# }
# 
# # Function to close the cluster
# close_cluster <- function(cl) {
#   parallel::stopCluster(cl) 
# }
# 
# ## Set up the simulation parameters
# {
#   Nsim <- 1e5
#   sample_size <- c(8, 10, 15, 20, 25, 30)
#   distribution <- c("Normal", "Exponential", "LogNormal")
#   #distribution <- "Exponential"
#   alpha <- 0.05
#   B <- 1e3
#   effect_size <- 0.0
# 
# }
# 
# # Progress taskbar setup
# {
#   my_cl <- par_set(cores_reserve = 2)
#   ntasks <- length(sample_size) * length(distribution) 
#   pb <- txtProgressBar(max=ntasks, style=3)
#   progress <- function(n) setTxtProgressBar(pb, n)
#   opts <- list(progress=progress)
# }
# 
# # Track simulation start time
# start_time <- Sys.time()
# cat("Simulation started at:", format(start_time), "\n\n")
# 
# ## Perform simulation
# #system.time({
#   sim_out <- foreach(n = sample_size,
#                      .packages = c("LaplacesDemon", "VGAM"), # Put Difficult Packages here
#                      .options.snow=opts) %:%
#     foreach(dist = distribution) %dopar%
#     {
#       set.seed(12345) 
#       pval_sw <- pval_t <- pval_perm <- pval_adaptive_t_perm <- pval_conditional <- numeric(Nsim) 
#       for (i in 1:Nsim) {
#         x <- generate_data(n, dist) 
#         y <- generate_data(n, dist) 
#         
#         # perform Shapiro-Wilk test
#         pval_sw[i] <- shapiro.test(x)$p.value
#         # perform t-test
#         pval_t[i] <- t.test(x, y, mu = effect_size)$p.value
#         # perform permutation test
#         observe_stat <- TwoSample_test_statistic(x, y)
#         data <- c(x, y)
#         permuted_stat <- numeric(B)
#         for (j in 1:B) {
#           sample_data <- sample(data)
#           sample_x <- sample_data[1:length(x)]
#           sample_y <- sample_data[(length(x) + 1):(length(x) + length(y))]
#           permuted_stat[j] <- TwoSample_test_statistic(sample_x, sample_y + effect_size) 
#         }
#         pval_perm[i] <- mean(abs(permuted_stat) >= abs(observe_stat))
#         # Adaptive t/permutation
#         if(pval_sw[i] > alpha){
#           pval_adaptive_t_perm[i] <- t.test(x, y, mu = effect_size)$p.value
#         } else {
#           observe_stat <- TwoSample_test_statistic(x, y)
#           data <- c(x, y)
#           permuted_stat <- numeric(B)
#           for (j in 1:B) {
#             sample_data <- sample(data)
#             sample_x <- sample_data[1:length(x)]
#             sample_y <- sample_data[(length(x) + 1):(length(x) + length(y))]
#             permuted_stat[j] <- TwoSample_test_statistic(sample_x, sample_y + effect_size)
#           }
#           pval_adaptive_t_perm[i] <- mean(abs(permuted_stat) >= abs(observe_stat))
#         }
#         # Conditional t-test error only if both samples are normal
#         if (pval_sw[i] > alpha && shapiro.test(y)$p.value > alpha) {
#           pval_conditional[i] <- t.test(x, y, mu = effect_size)$p.value
#         } else {
#           pval_conditional[i] <- NA
#         }
#         
#       }
#       # calculate results
#       results <- list(power_sw = mean(pval_sw < alpha),
#                       error_t = mean(pval_t < alpha),
#                       error_perm = mean(pval_perm < alpha),
#                       error_adaptive_t_perm = mean(pval_adaptive_t_perm < alpha),
#                       error_conditional = round(mean(pval_conditional < alpha, na.rm = TRUE), 3))
#       return(results)
#       #return(list(pval_sw = pval_sw,pval_t = pval_t, pval_perm = pval_perm, pval_adaptive_t_perm = pval_adaptive_t_perm,pval_conditional = pval_conditional))
#     }
#  
#   # Organize Results in tables
#   errorvec <- numeric(length(sample_size) * length(distribution))
#   power_sw.test <- Type_I_error_t.test <- Type_I_error_perm.test <- Type_I_error_adaptive_t_perm.test <- Type_I_error_conditional.test <- array(errorvec, dim = c(length(sample_size), length(distribution)), dimnames = list(sample_size, distribution))
#   for (t in seq_along(sample_size)) {
#     for (j in seq_along(distribution)) {
#       power_sw.test[t, j] <- (sim_out[[t]][[j]]$power_sw)
#       Type_I_error_t.test[t, j] <- (sim_out[[t]][[j]]$error_t)
#       Type_I_error_perm.test[t, j] <- (sim_out[[t]][[j]]$error_perm)
#       Type_I_error_adaptive_t_perm.test[t, j] <- (sim_out[[t]][[j]]$error_adaptive_t_perm)
#       Type_I_error_conditional.test[t, j] <- (sim_out[[t]][[j]]$error_conditional)
#     }
#   }
# #})
#   
# # Track end time
# end_time <- Sys.time()
# cat("\n\nSimulation completed at:", format(end_time), "\n")
# cat("Total runtime:", round(difftime(end_time, start_time, units = "mins"), 2), "minutes\n")
# 
# #close clusters  
# close_cluster(my_cl) 
# 
# #print results
# power_sw.test
# Type_I_error_t.test
# Type_I_error_perm.test
# Type_I_error_adaptive_t_perm.test
# Type_I_error_conditional.test
# 
# # Save results
# write.csv(power_sw.test, "power_sw_test.csv")
# write.csv(Type_I_error_t.test, "error_t_test.csv")
# write.csv(Type_I_error_perm.test, "error_permutation_test.csv")
# write.csv(Type_I_error_adaptive_t_perm.test, "error_t_perm_test.csv")
# write.csv(Type_I_error_conditional.test, "error_conditional_test.csv")
```


```{r}
# # save RData
# save(power_sw.test, Type_I_error_t.test, Type_I_error_perm.test,Type_I_error_adaptive_t_perm.test, Type_I_error_conditional.test,  file = "twosample.Type_I_error.RData" )

```


```{r}
load("/Users/benedictkongyir/Desktop/OSU/Research/Pretest-Simulation/Simulation/SPRING2025/DOWNSTREAM TESTS/compare test methods_20250310/twosamples/twosamples/twosample_test_v6_20250320.RData")
plot_data <- data.frame(
  SampleSize = rep(sample_size, times = length(distribution) * 5),
  Distribution = rep(rep(distribution, each = length(sample_size)), times = 5),
  ErrorRate = c(as.vector(Type_I_error_t.test),
                as.vector(Type_I_error_perm.test),
                as.vector(Type_I_error_adaptive_t_perm.test),
                as.vector(Type_I_error_conditional.test),
                as.vector(power_sw.test)),
  Test = rep(c("t-test",  "Permutation", "adaptive t/perm",
               "Conditional t-test", "Shapiro-Wilk"),
             each = length(sample_size) * length(distribution))
)

# Filter out Normal distribution
#plot_data <- subset(plot_data, Distribution != "Normal")

# Define PlotType for row-based faceting
plot_data$PlotType <- ifelse(
  plot_data$Test == "Shapiro-Wilk", "SW Power",
  ifelse(plot_data$Test == "Conditional t-test", "Conditional Type I Error", "Type I Error")
)

# Convert PlotType to factor for ordering rows
plot_data$PlotType <- factor(plot_data$PlotType, levels = c("SW Power", "Type I Error", "Conditional Type I Error"))

# --- Plot using facet_grid (rows = PlotType, columns = Distribution) ---
# Base plot
p <- ggplot(plot_data, aes(x = SampleSize, y = ErrorRate, color = Test, linetype = Test)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  facet_grid(PlotType ~ Distribution, scales = "free_y") +
  labs(
    title = "Type I Error Rates, Shapiro-Wilk Power, and Conditional Type I Error by Distribution",
    x = "Sample Size",
    y = "Rate / Power"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")

# Add 0.05 reference lines **only to Type I Error plots**
p <- p + geom_hline(
  data = subset(plot_data, PlotType == "Type I Error"),
  aes(yintercept = 0.05),
  linetype = "dashed",
  color = "gray40"
)

p
# Save plot
ggsave("type1_error_sw_power_conditional_plot.png", p, width = 12, height = 10)

#save.image(paste0("twosample_test_v6_20250320",".RData"))

```


